[book]
authors = ["Alisue"]
language = "en"
multilingual = false
src = "src"
title = "Denops Documentation"

[output.html]
default-theme = "coal"
additional-js = ["assets/codeblock-title.js"]
additional-css = ["assets/codeblock-title.css"]

[preprocessor.alerts]
