[book]
authors = ["Alisue"]
language = "en"
multilingual = false
src = "src"
title = "Denops Documentation"

[output.html]
additional-css = ["theme/reference.css"]

[build]
build-dir = "docs"

[preprocessor.plantuml]
plantuml-cmd="http://www.plantuml.com/plantuml"
