name: Test

env:
  DENO_VERSION: 1.x
  MDBOOK_VERSION: 0.4.36

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            .tools/
          key: ${{ runner.os }}-cargo
      - uses: denoland/setup-deno@v1.1.4
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Install mdBook
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
          rustup update
          cargo install --force --version ${MDBOOK_VERSION} mdbook
          cargo install --force mdbook-alerts
      - name: Build with mdBook
        run: mdbook build
      - name: Format
        run: deno fmt --check
      - name: Misspell
        uses: reviewdog/action-misspell@v1.15.0
