name: Test

env:
  DENO_VERSION: 1.x

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            .tools/
          key: ${{ runner.os }}-cargo
      - uses: denoland/setup-deno@main
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Format
        run: make fmt-check
      - name: Install tools
        run: make tools
      - name: Generate
        run: |
          make gen
          git diff --check
